<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TerminalRenderer\TerminalRenderer.csproj" />
    <ProjectReference Include="..\TerminalTestingUiLib.Diagnostics\TerminalTestingUiLib.Diagnostics.csproj" />
  </ItemGroup>

</Project>
